id: I635575D2
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T18:58:25.211481'
last_modified: '2022-05-27T18:58:25.211494'
parser: null
source_metadata:
  title: 'MSV 5,00: Uttaragrantha 1'
  language: bo
  base:
    fFFB4:
      title: CI_Kaśmīr Upāliparipṛcchā
      base_file: fFFB4.txt
      order: 1
  chapter_to_tile:
    CI: Uttaragrantha 1
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
